import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} antialiased`}
    >
      <body>
        {children}
        <Toaster
          position="top-center"
          toastOptions={{
            classNames: {
              success: "!bg-primary !text-white !border-primary",
              error: "!bg-danger !text-white !border-danger",
              toast: "!rounded-2xl !shadow-xl",
              title: "!font-semibold",
            },
          }}
        />
      </body>
    </html>
  );
}
